name: Build New MID Images

on:
  push:
    branches: [master]
  schedule:
    - cron: "0 20 * * SAT"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Refresh the MIDs
        env:
          DOCKER_USER_NAME: ${{ secrets.DOCKER_USER_NAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
          MONGODB_NAME: ${{ secrets.MONGODB_NAME }}
          FORCE_REFRESH: ${{ secrets.FORCE_REFRESH }}
        run: |
          docker run --rm \
          --env DOCKER_USER_NAME \
          --env DOCKER_TOKEN \
          --env MONGODB_URL \
          --env MONGODB_NAME \
          --env FORCE_REFRESH \
          -v /var/run/docker.sock:/var/run/docker.sock \
          $(docker build -q .)
